CREATE TABLE "bot_messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"bot_id" text NOT NULL,
	"bot_name" text NOT NULL,
	"direction" text NOT NULL,
	"sender_name" text,
	"sender_address" text,
	"recipient_name" text,
	"recipient_address" text,
	"chat_guid" text,
	"chat_name" text,
	"message_text" text,
	"message_id" text,
	"has_media" boolean DEFAULT false,
	"media_type" text,
	"is_group" boolean DEFAULT false,
	"status" text NOT NULL,
	"error_text" text,
	"flagged" boolean DEFAULT false,
	"flag_reason" text,
	"token_count" integer,
	"response_time_ms" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"metadata" jsonb
);
